#!python
import re
import sys

from SoftLayer.CLI.core import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
   # print("arvs[0] = %s" % sys.argv[0])
    sys.exit(main())
