"""
    softlayer.cli.routes
    ~~~~~~~~~~~~~~~~~~~~~
    This is how all commands are registered with the cli.

    :license: MIT, see LICENSE for more details.
"""

ALL_ROUTES = [
    ('call-api', 'softlayer.cli.call_api:cli'),

    ('vs', 'softlayer.cli.virt'),
    ('vs:cancel', 'softlayer.cli.virt.cancel:cli'),
    ('vs:capture', 'softlayer.cli.virt.capture:cli'),
    ('vs:create', 'softlayer.cli.virt.create:cli'),
    ('vs:create-options', 'softlayer.cli.virt.create_options:cli'),
    ('vs:detail', 'softlayer.cli.virt.detail:cli'),
    ('vs:dns-sync', 'softlayer.cli.virt.dns:cli'),
    ('vs:edit', 'softlayer.cli.virt.edit:cli'),
    ('vs:list', 'softlayer.cli.virt.list:cli'),
    ('vs:network', 'softlayer.cli.virt.network:cli'),
    ('vs:pause', 'softlayer.cli.virt.power:pause'),
    ('vs:power_off', 'softlayer.cli.virt.power:power_off'),
    ('vs:power_on', 'softlayer.cli.virt.power:power_on'),
    ('vs:rescue', 'softlayer.cli.virt.power:rescue'),
    ('vs:resume', 'softlayer.cli.virt.power:resume'),
    ('vs:ready', 'softlayer.cli.virt.ready:cli'),
    ('vs:reboot', 'softlayer.cli.virt.power:reboot'),
    ('vs:reload', 'softlayer.cli.virt.reload:cli'),
    ('vs:upgrade', 'softlayer.cli.virt.upgrade:cli'),

    ('cdn', 'softlayer.cli.cdn'),
    ('cdn:detail', 'softlayer.cli.cdn.detail:cli'),
    ('cdn:list', 'softlayer.cli.cdn.list:cli'),
    ('cdn:load', 'softlayer.cli.cdn.load:cli'),
    ('cdn:origin-add', 'softlayer.cli.cdn.origin_add:cli'),
    ('cdn:origin-list', 'softlayer.cli.cdn.origin_list:cli'),
    ('cdn:origin-remove', 'softlayer.cli.cdn.origin_remove:cli'),
    ('cdn:purge', 'softlayer.cli.cdn.purge:cli'),

    ('config', 'softlayer.cli.config'),
    ('config:setup', 'softlayer.cli.config.setup:cli'),
    ('config:show', 'softlayer.cli.config.show:cli'),

    ('dns', 'softlayer.cli.dns'),
    ('dns:import', 'softlayer.cli.dns.zone_import:cli'),
    ('dns:record-add', 'softlayer.cli.dns.record_add:cli'),
    ('dns:record-edit', 'softlayer.cli.dns.record_edit:cli'),
    ('dns:record-list', 'softlayer.cli.dns.record_list:cli'),
    ('dns:record-remove', 'softlayer.cli.dns.record_remove:cli'),
    ('dns:zone-create', 'softlayer.cli.dns.zone_create:cli'),
    ('dns:zone-delete', 'softlayer.cli.dns.zone_delete:cli'),
    ('dns:zone-list', 'softlayer.cli.dns.zone_list:cli'),
    ('dns:zone-print', 'softlayer.cli.dns.zone_print:cli'),

    ('firewall', 'softlayer.cli.firewall'),
    ('firewall:add', 'softlayer.cli.firewall.add:cli'),
    ('firewall:cancel', 'softlayer.cli.firewall.cancel:cli'),
    ('firewall:detail', 'softlayer.cli.firewall.detail:cli'),
    ('firewall:edit', 'softlayer.cli.firewall.edit:cli'),
    ('firewall:list', 'softlayer.cli.firewall.list:cli'),

    ('globalip', 'softlayer.cli.globalip'),
    ('globalip:assign', 'softlayer.cli.globalip.assign:cli'),
    ('globalip:cancel', 'softlayer.cli.globalip.cancel:cli'),
    ('globalip:create', 'softlayer.cli.globalip.create:cli'),
    ('globalip:list', 'softlayer.cli.globalip.list:cli'),
    ('globalip:unassign', 'softlayer.cli.globalip.unassign:cli'),

    ('image', 'softlayer.cli.image'),
    ('image:delete', 'softlayer.cli.image.delete:cli'),
    ('image:detail', 'softlayer.cli.image.detail:cli'),
    ('image:edit', 'softlayer.cli.image.edit:cli'),
    ('image:list', 'softlayer.cli.image.list:cli'),

    ('iscsi', 'softlayer.cli.iscsi'),
    ('iscsi:cancel', 'softlayer.cli.iscsi.cancel:cli'),
    ('iscsi:create', 'softlayer.cli.iscsi.create:cli'),
    ('iscsi:detail', 'softlayer.cli.iscsi.detail:cli'),
    ('iscsi:list', 'softlayer.cli.iscsi.list:cli'),

    ('loadbal', 'softlayer.cli.loadbal'),
    ('loadbal:cancel', 'softlayer.cli.loadbal.cancel:cli'),
    ('loadbal:create', 'softlayer.cli.loadbal.create:cli'),
    ('loadbal:create-options', 'softlayer.cli.loadbal.create_options:cli'),
    ('loadbal:detail', 'softlayer.cli.loadbal.detail:cli'),
    ('loadbal:group-add', 'softlayer.cli.loadbal.group_add:cli'),
    ('loadbal:group-delete', 'softlayer.cli.loadbal.group_delete:cli'),
    ('loadbal:group-edit', 'softlayer.cli.loadbal.group_edit:cli'),
    ('loadbal:group-reset', 'softlayer.cli.loadbal.group_reset:cli'),
    ('loadbal:health-checks', 'softlayer.cli.loadbal.health_checks:cli'),
    ('loadbal:list', 'softlayer.cli.loadbal.list:cli'),
    ('loadbal:routing-methods', 'softlayer.cli.loadbal.routing_methods:cli'),
    ('loadbal:routing-types', 'softlayer.cli.loadbal.routing_types:cli'),
    ('loadbal:service-add', 'softlayer.cli.loadbal.service_add:cli'),
    ('loadbal:service-delete', 'softlayer.cli.loadbal.service_delete:cli'),
    ('loadbal:service-edit', 'softlayer.cli.loadbal.service_edit:cli'),
    ('loadbal:service-toggle', 'softlayer.cli.loadbal.service_toggle:cli'),

    ('messaging', 'softlayer.cli.mq'),
    ('messaging:accounts-list', 'softlayer.cli.mq.accounts_list:cli'),
    ('messaging:endpoints-list', 'softlayer.cli.mq.endpoints_list:cli'),
    ('messaging:ping', 'softlayer.cli.mq.ping:cli'),
    ('messaging:queue-add', 'softlayer.cli.mq.queue_add:cli'),
    ('messaging:queue-detail', 'softlayer.cli.mq.queue_detail:cli'),
    ('messaging:queue-edit', 'softlayer.cli.mq.queue_edit:cli'),
    ('messaging:queue-list', 'softlayer.cli.mq.queue_list:cli'),
    ('messaging:queue-pop', 'softlayer.cli.mq.queue_pop:cli'),
    ('messaging:queue-push', 'softlayer.cli.mq.queue_push:cli'),
    ('messaging:queue-remove', 'softlayer.cli.mq.queue_remove:cli'),
    ('messaging:topic-add', 'softlayer.cli.mq.topic_add:cli'),
    ('messaging:topic-detail', 'softlayer.cli.mq.topic_detail:cli'),
    ('messaging:topic-list', 'softlayer.cli.mq.topic_list:cli'),
    ('messaging:topic-push', 'softlayer.cli.mq.topic_push:cli'),
    ('messaging:topic-remove', 'softlayer.cli.mq.topic_remove:cli'),
    ('messaging:topic-subscribe', 'softlayer.cli.mq.topic_subscribe:cli'),
    ('messaging:topic-unsubscribe', 'softlayer.cli.mq.topic_unsubscribe:cli'),

    ('metadata', 'softlayer.cli.metadata:cli'),

    ('nas', 'softlayer.cli.nas'),
    ('nas:list', 'softlayer.cli.nas.list:cli'),

    ('rwhois', 'softlayer.cli.rwhois'),
    ('rwhois:edit', 'softlayer.cli.rwhois.edit:cli'),
    ('rwhois:show', 'softlayer.cli.rwhois.show:cli'),

    ('server', 'softlayer.cli.server'),
    ('server:cancel', 'softlayer.cli.server.cancel:cli'),
    ('server:cancel-reasons', 'softlayer.cli.server.cancel_reasons:cli'),
    ('server:create', 'softlayer.cli.server.create:cli'),
    ('server:create-options', 'softlayer.cli.server.create_options:cli'),
    ('server:detail', 'softlayer.cli.server.detail:cli'),
    ('server:edit', 'softlayer.cli.server.edit:cli'),
    ('server:list', 'softlayer.cli.server.list:cli'),
    ('server:list-chassis', 'softlayer.cli.server.list_chassis:cli'),
    ('server:nic-edit', 'softlayer.cli.server.nic_edit:cli'),
    ('server:power-cycle', 'softlayer.cli.server.power:power_cycle'),
    ('server:power-off', 'softlayer.cli.server.power:power_off'),
    ('server:power-on', 'softlayer.cli.server.power:power_on'),
    ('server:reboot', 'softlayer.cli.server.power:reboot'),
    ('server:reload', 'softlayer.cli.server.reload:cli'),

    ('snapshot', 'softlayer.cli.snapshot'),
    ('snapshot:cancel', 'softlayer.cli.snapshot.cancel:cli'),
    ('snapshot:create', 'softlayer.cli.snapshot.create:cli'),
    ('snapshot:create-space', 'softlayer.cli.snapshot.create_space:cli'),
    ('snapshot:list', 'softlayer.cli.snapshot.list:cli'),
    ('snapshot:restore-volume', 'softlayer.cli.snapshot.restore_volume:cli'),

    ('sshkey', 'softlayer.cli.sshkey'),
    ('sshkey:add', 'softlayer.cli.sshkey.add:cli'),
    ('sshkey:remove', 'softlayer.cli.sshkey.remove:cli'),
    ('sshkey:edit', 'softlayer.cli.sshkey.edit:cli'),
    ('sshkey:list', 'softlayer.cli.sshkey.list:cli'),
    ('sshkey:print', 'softlayer.cli.sshkey.print:cli'),

    ('ssl', 'softlayer.cli.ssl'),
    ('ssl:add', 'softlayer.cli.ssl.add:cli'),
    ('ssl:download', 'softlayer.cli.ssl.download:cli'),
    ('ssl:edit', 'softlayer.cli.ssl.edit:cli'),
    ('ssl:list', 'softlayer.cli.ssl.list:cli'),
    ('ssl:remove', 'softlayer.cli.ssl.remove:cli'),

    ('subnet', 'softlayer.cli.subnet'),
    ('subnet:cancel', 'softlayer.cli.subnet.cancel:cli'),
    ('subnet:create', 'softlayer.cli.subnet.create:cli'),
    ('subnet:detail', 'softlayer.cli.subnet.detail:cli'),
    ('subnet:list', 'softlayer.cli.subnet.list:cli'),
    ('subnet:lookup', 'softlayer.cli.subnet.lookup:cli'),

    ('ticket', 'softlayer.cli.ticket'),
    ('ticket:create', 'softlayer.cli.ticket.create:cli'),
    ('ticket:detail', 'softlayer.cli.ticket.detail:cli'),
    ('ticket:list', 'softlayer.cli.ticket.list:cli'),
    ('ticket:update', 'softlayer.cli.ticket.update:cli'),
    ('ticket:subjects', 'softlayer.cli.ticket.subjects:cli'),
    ('ticket:summary', 'softlayer.cli.ticket.summary:cli'),

    ('vlan', 'softlayer.cli.vlan'),
    ('vlan:detail', 'softlayer.cli.vlan.detail:cli'),
    ('vlan:list', 'softlayer.cli.vlan.list:cli'),

    ('summary', 'softlayer.cli.summary:cli'),
]

ALL_ALIASES = {
    'meta': 'metadata',
    'my': 'metadata',
    'vm': 'vs',
    'hardware': 'server',
    'hw': 'server',
    'bmetal': 'bmc',
    'virtual': 'vs',
    'lb': 'loadbal',
}
