"""
    SoftLayer.vs_capacity
    ~~~~~~~~~~~~~~~~~~~~~~~
    Reserved Capacity Manager and helpers

    :license: MIT, see License for more details.
"""

import logging
import SoftLayer

from SoftLayer.managers import ordering
from SoftLayer import utils

from pprint import pprint as pp
# Invalid names are ignored due to long method names and short argument names
# pylint: disable=invalid-name, no-self-use

LOGGER = logging.getLogger(__name__)

class CapacityManager(utils.IdentifierMixin, object):
    """Manages SoftLayer Dedicated Hosts.

        See product information here https://www.ibm.com/cloud/dedicated


    :param SoftLayer.API.BaseClient client: the client instance
    :param SoftLayer.managers.OrderingManager ordering_manager: an optional manager to handle ordering.
                                              If none is provided, one will be auto initialized.
    """

    def __init__(self, client, ordering_manager=None):
        self.client = client
        self.account = client['Account']
        self.capacity_package = 'RESERVED_CAPACITY'

        if ordering_manager is None:
            self.ordering_manager = ordering.OrderingManager(client)

    def list(self):
        results = self.client.call('Account', 'getReservedCapacityGroups')
        return results

    def get_create_options(self):
        mask = "mask[attributes,prices[pricingLocationGroup]]"
        # mask = "mask[id, description, capacity, units]"
        results = self.ordering_manager.list_items(self.capacity_package, mask=mask)
        return results

    def get_available_routers(self):
        """Pulls down all backendRouterIds that are available"""
        mask = "mask[locations]"
        # Step 1, get the package id
        package = self.ordering_manager.get_package_by_key(self.capacity_package, mask="id")

        # Step 2, get the regions this package is orderable in
        regions = self.client.call('Product_Package', 'getRegions', id=package['id'], mask=mask)
        _filter = {'datacenterName': {'operation': ''}}
        routers = {}

        # Step 3, for each location in each region, get the pod details, which contains the router id
        for region  in regions:
            routers[region['keyname']] = []
            for location in region['locations']:
                location['location']['pods'] = list()
                _filter['datacenterName']['operation'] = location['location']['name']
                location['location']['pods'] = self.client.call('Network_Pod', 'getAllObjects', filter=_filter)

        # Step 4, return the data.
        return regions

    def create(self, name, datacenter, backend_router_id, capacity, quantity, test=False):
        """Orders a Virtual_ReservedCapacityGroup"""
        args = (self.capacity_package, datacenter, [capacity])
        extras = {"backendRouterId": backend_router_id, "name": name}
        kwargs = {
            'extras': extras,
            'quantity': quantity,
            'complex_type': 'SoftLayer_Container_Product_Order_Virtual_ReservedCapacity',
            'hourly': True
        }
        if test:
            receipt = self.ordering_manager.verify_order(*args, **kwargs)
        else:
            receipt = self.ordering_manager.place_order(*args, **kwargs)
        return receipt



"""
{'orderDate': '2018-09-20T16:48:32-06:00',
 'orderDetails': {'bigDataOrderFlag': False,
                  'billingInformation': {'billingAddressLine1': 'Addr1 307608',
                                         'billingAddressLine2': 'Addr2 307608',
                                         'billingCity': 'Dallas',
                                         'billingCountryCode': 'US',
                                         'billingEmail': 'noreply@softlayer.com',
                                         'billingNameCompany': 'Customer '
                                                               '307608',
                                         'billingNameFirst': 'FName THREE '
                                                             'HUNDRED SEVEN '
                                                             'THOU',
                                         'billingNameLast': 'LName THREE '
                                                            'HUNDRED SEVEN '
                                                            'THOU',
                                         'billingPhoneVoice': '0000307608',
                                         'billingPostalCode': '75244-4608',
                                         'billingState': 'TX',
                                         'cardExpirationMonth': '',
                                         'cardExpirationYear': '',
                                         'euSupported': '',
                                         'taxExempt': 0},
                  'billingOrderItemId': '',
                  'containerSplHash': '0000000065689e3f00007f66446132d6',
                  'currencyShortName': 'USD',
                  'extendedHardwareTesting': '',
                  'gdprConsentFlag': '',
                  'imageTemplateId': '',
                  'isManagedOrder': '',
                  'message': '',
                  'orderContainers': [{'backendRouterId': 1079095,
                                       'bigDataOrderFlag': False,
                                       'billingOrderItemId': '',
                                       'containerSplHash': '0000000065689e3400007f66446132d6',
                                       'currencyShortName': 'USD',
                                       'extendedHardwareTesting': '',
                                       'gdprConsentFlag': '',
                                       'imageTemplateId': '',
                                       'isManagedOrder': '',
                                       'itemCategoryQuestionAnswers': [],
                                       'location': '1854895',
                                       'locationObject': {'id': 1854895,
                                                          'longName': 'Dallas '
                                                                      '13',
                                                          'name': 'dal13'},
                                       'message': '',
                                       'name': 'cgallo-test-01',
                                       'packageId': 1059,
                                       'paymentType': '',
                                       'postTaxRecurring': '6.17',
                                       'postTaxRecurringHourly': '6.17',
                                       'postTaxRecurringMonthly': '0',
                                       'postTaxSetup': '0',
                                       'preTaxRecurring': '6.17',
                                       'preTaxRecurringHourly': '6.17',
                                       'preTaxRecurringMonthly': '0',
                                       'preTaxSetup': '0',
                                       'presetId': '',
                                       'prices': [{'categories': [{'categoryCode': 'reserved_capacity',
                                                                   'id': 2060,
                                                                   'name': 'Reserved '
                                                                           'Capacity'}],
                                                   'hourlyRecurringFee': '.617',
                                                   'id': 217633,
                                                   'item': {'bundle': [{'bundleItem': {'capacity': '12',
                                                                                       'description': 'B1.16x64 '
                                                                                                      '(1 '
                                                                                                      'Year '
                                                                                                      'Term)',
                                                                                       'id': 12309,
                                                                                       'keyName': 'B1_16X64_1_YEAR_TERM',
                                                                                       'units': 'MONTHS'},
                                                                        'bundleItemId': 12309,
                                                                        'category': {'categoryCode': 'guest_core',
                                                                                     'id': 80,
                                                                                     'name': 'Computing '
                                                                                             'Instance'},
                                                                        'id': 44720,
                                                                        'itemPrice': {'hourlyRecurringFee': '0',
                                                                                      'id': 210185,
                                                                                      'itemId': 1194,
                                                                                      'laborFee': '0',
                                                                                      'oneTimeFee': '0',
                                                                                      'recurringFee': '0',
                                                                                      'setupFee': '0'},
                                                                        'itemPriceId': 210185},
                                                                       {'bundleItem': {'capacity': '12',
                                                                                       'description': 'B1.16x64 '
                                                                                                      '(1 '
                                                                                                      'Year '
                                                                                                      'Term)',
                                                                                       'id': 12309,
                                                                                       'keyName': 'B1_16X64_1_YEAR_TERM',
                                                                                       'units': 'MONTHS'},
                                                                        'bundleItemId': 12309,
                                                                        'category': {'categoryCode': 'ram',
                                                                                     'id': 3,
                                                                                     'name': 'RAM'},
                                                                        'id': 44726,
                                                                        'itemPrice': {'hourlyRecurringFee': '0',
                                                                                      'id': 216607,
                                                                                      'itemId': 10575,
                                                                                      'laborFee': '0',
                                                                                      'oneTimeFee': '0',
                                                                                      'recurringFee': '0',
                                                                                      'setupFee': '0'},
                                                                        'itemPriceId': 216607}],
                                                            'capacity': '12',
                                                            'description': 'B1.16x64 '
                                                                           '(1 '
                                                                           'Year '
                                                                           'Term)',
                                                            'id': 12309,
                                                            'keyName': 'B1_16X64_1_YEAR_TERM',
                                                            'thirdPartyPolicyAssignments': [],
                                                            'units': 'MONTHS'},
                                                   'itemId': 12309,
                                                   'laborFee': '0',
                                                   'oneTimeFee': '0',
                                                   'recurringFee': '0',
                                                   'setupFee': '0'}],
                                       'primaryDiskPartitionId': '',
                                       'privateCloudOrderFlag': False,
                                       'proratedInitialCharge': '0',
                                       'proratedOrderTotal': '0',
                                       'quantity': 10,
                                       'resourceGroupId': '',
                                       'resourceGroupTemplateId': '',
                                       'sendQuoteEmailFlag': '',
                                       'serverCoreCount': '',
                                       'sourceVirtualGuestId': '',
                                       'sshKeys': [],
                                       'stepId': '',
                                       'storageGroups': [],
                                       'taxCacheHash': '2ce690dee89b73a1653785d3032af6c5d5dd88de',
                                       'taxCompletedFlag': False,
                                       'totalRecurringTax': '0',
                                       'totalSetupTax': '0',
                                       'useHourlyPricing': True}],
                  'packageId': '',
                  'paymentType': 'ADD_TO_BALANCE',
                  'postTaxRecurring': '6.17',
                  'postTaxRecurringHourly': '6.17',
                  'postTaxRecurringMonthly': '0',
                  'postTaxSetup': '0',
                  'preTaxRecurring': '6.17',
                  'preTaxRecurringHourly': '6.17',
                  'preTaxRecurringMonthly': '0',
                  'preTaxSetup': '0',
                  'presetId': '',
                  'prices': [],
                  'primaryDiskPartitionId': '',
                  'privateCloudOrderFlag': False,
                  'properties': [],
                  'proratedInitialCharge': '0',
                  'proratedOrderTotal': '0',
                  'quantity': '',
                  'resourceGroupId': '',
                  'resourceGroupTemplateId': '',
                  'sendQuoteEmailFlag': '',
                  'serverCoreCount': '',
                  'sourceVirtualGuestId': '',
                  'sshKeys': [],
                  'stepId': '',
                  'storageGroups': [],
                  'taxCompletedFlag': False,
                  'totalRecurringTax': '0',
                  'totalSetupTax': '0',
                  'useHourlyPricing': ''},
 'orderId': 29297264,
 'placedOrder': {'account': {'brandId': 2,
                             'companyName': 'Customer 307608',
                             'id': 307608},
                 'accountId': 307608,
                 'id': 29297264,
                 'items': [{'categoryCode': 'reserved_capacity',
                            'children': [{'categoryCode': 'guest_core',
                                          'description': '16 x 2.0 GHz or '
                                                         'higher Cores',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550142,
                                          'itemId': 1194,
                                          'itemPriceId': '210185',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550140,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'},
                                         {'categoryCode': 'ram',
                                          'description': '64 GB',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550144,
                                          'itemId': 10575,
                                          'itemPriceId': '216607',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550140,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'}],
                            'description': 'B1.16x64 (1 Year Term)',
                            'hourlyRecurringFee': '.617',
                            'id': 371550140,
                            'itemId': 12309,
                            'itemPriceId': '217633',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': '',
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'guest_core',
                            'description': '16 x 2.0 GHz or higher Cores',
                            'hourlyRecurringFee': '0',
                            'id': 371550142,
                            'itemId': 1194,
                            'itemPriceId': '210185',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550140,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'ram',
                            'description': '64 GB',
                            'hourlyRecurringFee': '0',
                            'id': 371550144,
                            'itemId': 10575,
                            'itemPriceId': '216607',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550140,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'reserved_capacity',
                            'children': [{'categoryCode': 'guest_core',
                                          'description': '16 x 2.0 GHz or '
                                                         'higher Cores',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550148,
                                          'itemId': 1194,
                                          'itemPriceId': '210185',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550146,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'},
                                         {'categoryCode': 'ram',
                                          'description': '64 GB',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550150,
                                          'itemId': 10575,
                                          'itemPriceId': '216607',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550146,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'}],
                            'description': 'B1.16x64 (1 Year Term)',
                            'hourlyRecurringFee': '.617',
                            'id': 371550146,
                            'itemId': 12309,
                            'itemPriceId': '217633',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': '',
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'guest_core',
                            'description': '16 x 2.0 GHz or higher Cores',
                            'hourlyRecurringFee': '0',
                            'id': 371550148,
                            'itemId': 1194,
                            'itemPriceId': '210185',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550146,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'ram',
                            'description': '64 GB',
                            'hourlyRecurringFee': '0',
                            'id': 371550150,
                            'itemId': 10575,
                            'itemPriceId': '216607',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550146,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'reserved_capacity',
                            'children': [{'categoryCode': 'guest_core',
                                          'description': '16 x 2.0 GHz or '
                                                         'higher Cores',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550154,
                                          'itemId': 1194,
                                          'itemPriceId': '210185',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550152,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'},
                                         {'categoryCode': 'ram',
                                          'description': '64 GB',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550156,
                                          'itemId': 10575,
                                          'itemPriceId': '216607',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550152,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'}],
                            'description': 'B1.16x64 (1 Year Term)',
                            'hourlyRecurringFee': '.617',
                            'id': 371550152,
                            'itemId': 12309,
                            'itemPriceId': '217633',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': '',
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'guest_core',
                            'description': '16 x 2.0 GHz or higher Cores',
                            'hourlyRecurringFee': '0',
                            'id': 371550154,
                            'itemId': 1194,
                            'itemPriceId': '210185',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550152,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'ram',
                            'description': '64 GB',
                            'hourlyRecurringFee': '0',
                            'id': 371550156,
                            'itemId': 10575,
                            'itemPriceId': '216607',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550152,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'reserved_capacity',
                            'children': [{'categoryCode': 'guest_core',
                                          'description': '16 x 2.0 GHz or '
                                                         'higher Cores',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550160,
                                          'itemId': 1194,
                                          'itemPriceId': '210185',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550158,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'},
                                         {'categoryCode': 'ram',
                                          'description': '64 GB',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550162,
                                          'itemId': 10575,
                                          'itemPriceId': '216607',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550158,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'}],
                            'description': 'B1.16x64 (1 Year Term)',
                            'hourlyRecurringFee': '.617',
                            'id': 371550158,
                            'itemId': 12309,
                            'itemPriceId': '217633',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': '',
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'guest_core',
                            'description': '16 x 2.0 GHz or higher Cores',
                            'hourlyRecurringFee': '0',
                            'id': 371550160,
                            'itemId': 1194,
                            'itemPriceId': '210185',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550158,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'ram',
                            'description': '64 GB',
                            'hourlyRecurringFee': '0',
                            'id': 371550162,
                            'itemId': 10575,
                            'itemPriceId': '216607',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550158,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'reserved_capacity',
                            'children': [{'categoryCode': 'guest_core',
                                          'description': '16 x 2.0 GHz or '
                                                         'higher Cores',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550166,
                                          'itemId': 1194,
                                          'itemPriceId': '210185',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550164,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'},
                                         {'categoryCode': 'ram',
                                          'description': '64 GB',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550168,
                                          'itemId': 10575,
                                          'itemPriceId': '216607',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550164,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'}],
                            'description': 'B1.16x64 (1 Year Term)',
                            'hourlyRecurringFee': '.617',
                            'id': 371550164,
                            'itemId': 12309,
                            'itemPriceId': '217633',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': '',
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'guest_core',
                            'description': '16 x 2.0 GHz or higher Cores',
                            'hourlyRecurringFee': '0',
                            'id': 371550166,
                            'itemId': 1194,
                            'itemPriceId': '210185',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550164,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'ram',
                            'description': '64 GB',
                            'hourlyRecurringFee': '0',
                            'id': 371550168,
                            'itemId': 10575,
                            'itemPriceId': '216607',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550164,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'reserved_capacity',
                            'children': [{'categoryCode': 'guest_core',
                                          'description': '16 x 2.0 GHz or '
                                                         'higher Cores',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550172,
                                          'itemId': 1194,
                                          'itemPriceId': '210185',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550170,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'},
                                         {'categoryCode': 'ram',
                                          'description': '64 GB',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550174,
                                          'itemId': 10575,
                                          'itemPriceId': '216607',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550170,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'}],
                            'description': 'B1.16x64 (1 Year Term)',
                            'hourlyRecurringFee': '.617',
                            'id': 371550170,
                            'itemId': 12309,
                            'itemPriceId': '217633',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': '',
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'guest_core',
                            'description': '16 x 2.0 GHz or higher Cores',
                            'hourlyRecurringFee': '0',
                            'id': 371550172,
                            'itemId': 1194,
                            'itemPriceId': '210185',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550170,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'ram',
                            'description': '64 GB',
                            'hourlyRecurringFee': '0',
                            'id': 371550174,
                            'itemId': 10575,
                            'itemPriceId': '216607',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550170,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'reserved_capacity',
                            'children': [{'categoryCode': 'guest_core',
                                          'description': '16 x 2.0 GHz or '
                                                         'higher Cores',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550178,
                                          'itemId': 1194,
                                          'itemPriceId': '210185',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550176,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'},
                                         {'categoryCode': 'ram',
                                          'description': '64 GB',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550180,
                                          'itemId': 10575,
                                          'itemPriceId': '216607',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550176,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'}],
                            'description': 'B1.16x64 (1 Year Term)',
                            'hourlyRecurringFee': '.617',
                            'id': 371550176,
                            'itemId': 12309,
                            'itemPriceId': '217633',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': '',
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'guest_core',
                            'description': '16 x 2.0 GHz or higher Cores',
                            'hourlyRecurringFee': '0',
                            'id': 371550178,
                            'itemId': 1194,
                            'itemPriceId': '210185',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550176,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'ram',
                            'description': '64 GB',
                            'hourlyRecurringFee': '0',
                            'id': 371550180,
                            'itemId': 10575,
                            'itemPriceId': '216607',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550176,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'reserved_capacity',
                            'children': [{'categoryCode': 'guest_core',
                                          'description': '16 x 2.0 GHz or '
                                                         'higher Cores',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550184,
                                          'itemId': 1194,
                                          'itemPriceId': '210185',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550182,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'},
                                         {'categoryCode': 'ram',
                                          'description': '64 GB',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550186,
                                          'itemId': 10575,
                                          'itemPriceId': '216607',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550182,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'}],
                            'description': 'B1.16x64 (1 Year Term)',
                            'hourlyRecurringFee': '.617',
                            'id': 371550182,
                            'itemId': 12309,
                            'itemPriceId': '217633',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': '',
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'guest_core',
                            'description': '16 x 2.0 GHz or higher Cores',
                            'hourlyRecurringFee': '0',
                            'id': 371550184,
                            'itemId': 1194,
                            'itemPriceId': '210185',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550182,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'ram',
                            'description': '64 GB',
                            'hourlyRecurringFee': '0',
                            'id': 371550186,
                            'itemId': 10575,
                            'itemPriceId': '216607',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550182,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'reserved_capacity',
                            'children': [{'categoryCode': 'guest_core',
                                          'description': '16 x 2.0 GHz or '
                                                         'higher Cores',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550190,
                                          'itemId': 1194,
                                          'itemPriceId': '210185',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550188,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'},
                                         {'categoryCode': 'ram',
                                          'description': '64 GB',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550192,
                                          'itemId': 10575,
                                          'itemPriceId': '216607',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550188,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'}],
                            'description': 'B1.16x64 (1 Year Term)',
                            'hourlyRecurringFee': '.617',
                            'id': 371550188,
                            'itemId': 12309,
                            'itemPriceId': '217633',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': '',
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'guest_core',
                            'description': '16 x 2.0 GHz or higher Cores',
                            'hourlyRecurringFee': '0',
                            'id': 371550190,
                            'itemId': 1194,
                            'itemPriceId': '210185',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550188,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'ram',
                            'description': '64 GB',
                            'hourlyRecurringFee': '0',
                            'id': 371550192,
                            'itemId': 10575,
                            'itemPriceId': '216607',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550188,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'reserved_capacity',
                            'children': [{'categoryCode': 'guest_core',
                                          'description': '16 x 2.0 GHz or '
                                                         'higher Cores',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550196,
                                          'itemId': 1194,
                                          'itemPriceId': '210185',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550194,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'},
                                         {'categoryCode': 'ram',
                                          'description': '64 GB',
                                          'hourlyRecurringFee': '0',
                                          'id': 371550198,
                                          'itemId': 10575,
                                          'itemPriceId': '216607',
                                          'laborFee': '0',
                                          'oneTimeFee': '0',
                                          'parentId': 371550194,
                                          'promoCodeId': '',
                                          'recurringFee': '0',
                                          'setupFee': '0'}],
                            'description': 'B1.16x64 (1 Year Term)',
                            'hourlyRecurringFee': '.617',
                            'id': 371550194,
                            'itemId': 12309,
                            'itemPriceId': '217633',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': '',
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'guest_core',
                            'description': '16 x 2.0 GHz or higher Cores',
                            'hourlyRecurringFee': '0',
                            'id': 371550196,
                            'itemId': 1194,
                            'itemPriceId': '210185',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550194,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'},
                           {'categoryCode': 'ram',
                            'description': '64 GB',
                            'hourlyRecurringFee': '0',
                            'id': 371550198,
                            'itemId': 10575,
                            'itemPriceId': '216607',
                            'laborFee': '0',
                            'oneTimeFee': '0',
                            'parentId': 371550194,
                            'promoCodeId': '',
                            'recurringFee': '0',
                            'setupFee': '0'}],
                 'orderQuoteId': '',
                 'orderTypeId': 4,
                 'presaleEventId': '',
                 'status': 'PENDING_AUTO_APPROVAL',
                 'userRecord': {'accountId': 307608,
                                'firstName': 'Christopher',
                                'id': 167758,
                                'lastName': 'Gallo',
                                'username': 'SL307608'},
                 'userRecordId': 167758}}
"""